[project]
name = "squarem-jaxopt"
version = "0.1.0"
description = "SQUAREM acceleration for JAXopt solvers"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jax>=0.7.1",
    "jaxopt>=0.8.5",
]
